services:
    akeneo_connectivity.connection.webhook.guzzle_client:
        class: GuzzleHttp\Client

    akeneo_connectivity.connection.webhook.serializer.json_encoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    akeneo_connectivity.connection.webhook.webhook_client:
        class: Akeneo\Connectivity\Connection\Infrastructure\Webhook\Client\GuzzleWebhookClient
        arguments:
            - '@akeneo_connectivity.connection.webhook.guzzle_client'
            - '@akeneo_connectivity.connection.webhook.serializer.json_encoder'
            - '@logger'

    akeneo_connectivity.connection.webhook.webhook_event_builder:
        class: Akeneo\Connectivity\Connection\Application\Webhook\WebhookEventBuilder
        arguments:
            - !tagged akeneo_connectivity.connection.webhook.event_data_builder
